"""
Constructors and enum tables for the ISO 15118-20 Common Messages Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped iso20_generatedFunctionNumbersType: enum iso20_generatedFunctionNumbersType member 'iso20_AuthorizationReq' does not start with expected prefix 'iso20_generatedFunctionNumbersType_'

class powerToleranceAcceptanceType(Enum):
    PowerToleranceNotConfirmed = 0
    PowerToleranceConfirmed = 1


class evseNotificationType(Enum):
    Pause = 0
    ExitStandby = 1
    Terminate = 2
    ScheduleRenegotiation = 3
    ServiceRenegotiation = 4
    MeteringConfirmation = 5


class ecdhCurveType(Enum):
    SECP521 = 0
    X448 = 1


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class chargingSessionType(Enum):
    Pause = 0
    Terminate = 1
    ServiceRenegotiation = 2


class evCheckInStatusType(Enum):
    CheckIn = 0
    Processing = 1
    Completed = 2


class evCheckOutStatusType(Enum):
    CheckOut = 0
    Processing = 1
    Completed = 2


class authorizationType(Enum):
    EIM = 0
    PnC = 1


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class chargeProgressType(Enum):
    Start = 0
    Stop = 1
    Standby = 2
    ScheduleRenegotiation = 3


class parkingMethodType(Enum):
    AutoParking = 0
    MVGuideManual = 1
    Manual = 2


class evseCheckOutStatusType(Enum):
    Scheduled = 0
    Completed = 1


class channelSelectionType(Enum):
    Charge = 0
    Discharge = 1


def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def TransformsType(Transform:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PriceLevelScheduleEntryType(Duration:int, PriceLevel:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Duration": Duration,
        "PriceLevel": PriceLevel
    }
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ReferenceType(DigestMethod:dict[str, Any], DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def X509DataType(*, X509IssuerSerial:dict[str, Any]|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def RationalNumberType(Exponent:int, Value:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Exponent": Exponent,
        "Value": Value
    }
    return j

def PowerScheduleEntryType(Duration:int, Power:dict[str, Any], *, Power_L2:dict[str, Any]|None=None, Power_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Duration": Duration,
        "Power": Power
    }
    if Power_L2 is not None:
        j["Power_L2"] = Power_L2
    if Power_L3 is not None:
        j["Power_L3"] = Power_L3
    return j

def EVPriceRuleType(EnergyFee:dict[str, Any], PowerRangeStart:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "EnergyFee": EnergyFee,
        "PowerRangeStart": PowerRangeStart
    }
    return j

def EVPowerScheduleEntryType(Duration:int, Power:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Duration": Duration,
        "Power": Power
    }
    return j

def EVPriceRuleStackType(Duration:int, EVPriceRule:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "Duration": Duration,
        "EVPriceRule": {"arrayLen": len(EVPriceRule), "array": EVPriceRule}
    }
    return j

def PriceRuleType(EnergyFee:dict[str, Any], PowerRangeStart:dict[str, Any], *, ParkingFee:dict[str, Any]|None=None, ParkingFeePeriod:int|None=None, CarbonDioxideEmission:int|None=None, RenewableGenerationPercentage:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EnergyFee": EnergyFee,
        "PowerRangeStart": PowerRangeStart
    }
    if ParkingFee is not None:
        j["ParkingFee"] = ParkingFee
    if ParkingFeePeriod is not None:
        j["ParkingFeePeriod"] = ParkingFeePeriod
    if CarbonDioxideEmission is not None:
        j["CarbonDioxideEmission"] = CarbonDioxideEmission
    if RenewableGenerationPercentage is not None:
        j["RenewableGenerationPercentage"] = RenewableGenerationPercentage
    return j

def PowerScheduleEntryListType(PowerScheduleEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "PowerScheduleEntry": {"arrayLen": len(PowerScheduleEntry), "array": PowerScheduleEntry}
    }
    return j

def TaxRuleType(TaxRuleID:int, TaxRate:dict[str, Any], AppliesToEnergyFee:int, AppliesToParkingFee:int, AppliesToOverstayFee:int, AppliesMinimumMaximumCost:int, *, TaxRuleName:str|None=None, TaxIncludedInPrice:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TaxRuleID": TaxRuleID,
        "TaxRate": TaxRate,
        "AppliesToEnergyFee": AppliesToEnergyFee,
        "AppliesToParkingFee": AppliesToParkingFee,
        "AppliesToOverstayFee": AppliesToOverstayFee,
        "AppliesMinimumMaximumCost": AppliesMinimumMaximumCost
    }
    if TaxRuleName is not None:
        j["TaxRuleName"] = {"characters": [ord(c) for c in TaxRuleName], "charactersLen": len(TaxRuleName)}
    if TaxIncludedInPrice is not None:
        j["TaxIncludedInPrice"] = TaxIncludedInPrice
    return j

def PriceRuleStackType(Duration:int, PriceRule:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "Duration": Duration,
        "PriceRule": {"arrayLen": len(PriceRule), "array": PriceRule}
    }
    return j

def AdditionalServiceType(ServiceName:str, ServiceFee:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceName": {"characters": [ord(c) for c in ServiceName], "charactersLen": len(ServiceName)},
        "ServiceFee": ServiceFee
    }
    return j

def PowerScheduleType(TimeAnchor:int, PowerScheduleEntries:dict[str, Any], *, AvailableEnergy:dict[str, Any]|None=None, PowerTolerance:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "PowerScheduleEntries": PowerScheduleEntries
    }
    if AvailableEnergy is not None:
        j["AvailableEnergy"] = AvailableEnergy
    if PowerTolerance is not None:
        j["PowerTolerance"] = PowerTolerance
    return j

def EVPowerScheduleEntryListType(EVPowerScheduleEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPowerScheduleEntry": {"arrayLen": len(EVPowerScheduleEntry), "array": EVPowerScheduleEntry}
    }
    return j

def OverstayRuleType(StartTime:int, OverstayFee:dict[str, Any], OverstayFeePeriod:int, *, OverstayRuleDescription:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "StartTime": StartTime,
        "OverstayFee": OverstayFee,
        "OverstayFeePeriod": OverstayFeePeriod
    }
    if OverstayRuleDescription is not None:
        j["OverstayRuleDescription"] = {"characters": [ord(c) for c in OverstayRuleDescription], "charactersLen": len(OverstayRuleDescription)}
    return j

def EVPriceRuleStackListType(EVPriceRuleStack:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPriceRuleStack": {"arrayLen": len(EVPriceRuleStack), "array": EVPriceRuleStack}
    }
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:dict[str, Any], SignatureMethod:dict[str, Any], Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def EVPowerScheduleType(TimeAnchor:int, EVPowerScheduleEntries:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "EVPowerScheduleEntries": EVPowerScheduleEntries
    }
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SubCertificatesType(Certificate:list[bytearray])->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"arrayLen": len(Certificate), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in Certificate]}
    }
    return j

def ParameterType(Name:str, *, boolValue:int|None=None, byteValue:int|None=None, shortValue:int|None=None, intValue:int|None=None, rationalNumber:dict[str, Any]|None=None, finiteString:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Name": {"characters": [ord(c) for c in Name], "charactersLen": len(Name)}
    }
    if boolValue is not None:
        j["boolValue"] = boolValue
    if byteValue is not None:
        j["byteValue"] = byteValue
    if shortValue is not None:
        j["shortValue"] = shortValue
    if intValue is not None:
        j["intValue"] = intValue
    if rationalNumber is not None:
        j["rationalNumber"] = rationalNumber
    if finiteString is not None:
        j["finiteString"] = {"characters": [ord(c) for c in finiteString], "charactersLen": len(finiteString)}
    return j

def EVAbsolutePriceScheduleType(TimeAnchor:int, Currency:str, PriceAlgorithm:str, EVPriceRuleStacks:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "Currency": {"characters": [ord(c) for c in Currency], "charactersLen": len(Currency)},
        "PriceAlgorithm": {"characters": [ord(c) for c in PriceAlgorithm], "charactersLen": len(PriceAlgorithm)},
        "EVPriceRuleStacks": EVPriceRuleStacks
    }
    return j

def DetailedCostType(Amount:dict[str, Any], CostPerUnit:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Amount": Amount,
        "CostPerUnit": CostPerUnit
    }
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PriceLevelScheduleEntryListType(PriceLevelScheduleEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "PriceLevelScheduleEntry": {"arrayLen": len(PriceLevelScheduleEntry), "array": PriceLevelScheduleEntry}
    }
    return j

def DetailedTaxType(TaxRuleID:int, Amount:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TaxRuleID": TaxRuleID,
        "Amount": Amount
    }
    return j

def TaxRuleListType(TaxRule:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "TaxRule": {"arrayLen": len(TaxRule), "array": TaxRule}
    }
    return j

def PriceRuleStackListType(PriceRuleStack:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "PriceRuleStack": {"arrayLen": len(PriceRuleStack), "array": PriceRuleStack}
    }
    return j

def OverstayRuleListType(OverstayRule:list[dict[str, Any]], *, OverstayTimeThreshold:int|None=None, OverstayPowerThreshold:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "OverstayRule": {"arrayLen": len(OverstayRule), "array": OverstayRule}
    }
    if OverstayTimeThreshold is not None:
        j["OverstayTimeThreshold"] = OverstayTimeThreshold
    if OverstayPowerThreshold is not None:
        j["OverstayPowerThreshold"] = OverstayPowerThreshold
    return j

def AdditionalServiceListType(AdditionalService:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "AdditionalService": {"arrayLen": len(AdditionalService), "array": AdditionalService}
    }
    return j

def ServiceType(ServiceID:int, FreeService:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID,
        "FreeService": FreeService
    }
    return j

def ParameterSetType(ParameterSetID:int, Parameter:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSetID": ParameterSetID,
        "Parameter": {"arrayLen": len(Parameter), "array": Parameter}
    }
    return j

def SupportedProvidersListType(ProviderID:list[str])->dict[str, Any]:
    j:dict[str, Any] = {
        "ProviderID": {"arrayLen": len(ProviderID), "array": [{"characters": [ord(_c) for _c in _s], "charactersLen": len(_s)} for _s in ProviderID]}
    }
    return j

def ContractCertificateChainType(Certificate:bytearray, SubCertificates:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)},
        "SubCertificates": SubCertificates
    }
    return j

def Dynamic_EVPPTControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def MeterInfoType(MeterID:str, ChargedEnergyReadingWh:int, *, BPT_DischargedEnergyReadingWh:int|None=None, CapacitiveEnergyReadingVARh:int|None=None, BPT_InductiveEnergyReadingVARh:int|None=None, MeterSignature:bytearray|None=None, MeterStatus:int|None=None, MeterTimestamp:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "MeterID": {"characters": [ord(c) for c in MeterID], "charactersLen": len(MeterID)},
        "ChargedEnergyReadingWh": ChargedEnergyReadingWh
    }
    if BPT_DischargedEnergyReadingWh is not None:
        j["BPT_DischargedEnergyReadingWh"] = BPT_DischargedEnergyReadingWh
    if CapacitiveEnergyReadingVARh is not None:
        j["CapacitiveEnergyReadingVARh"] = CapacitiveEnergyReadingVARh
    if BPT_InductiveEnergyReadingVARh is not None:
        j["BPT_InductiveEnergyReadingVARh"] = BPT_InductiveEnergyReadingVARh
    if MeterSignature is not None:
        j["MeterSignature"] = {"bytes": list(MeterSignature), "bytesLen": len(MeterSignature)}
    if MeterStatus is not None:
        j["MeterStatus"] = MeterStatus
    if MeterTimestamp is not None:
        j["MeterTimestamp"] = MeterTimestamp
    return j

def SignatureType(SignedInfo:dict[str, Any], SignatureValue:dict[str, Any], *, Id:str|None=None, KeyInfo:dict[str, Any]|None=None, Object:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def Scheduled_EVPPTControlModeType(SelectedScheduleTupleID:int, *, PowerToleranceAcceptance:powerToleranceAcceptanceType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedScheduleTupleID": SelectedScheduleTupleID
    }
    if PowerToleranceAcceptance is not None:
        j["PowerToleranceAcceptance"] = PowerToleranceAcceptance.value
    return j

def ReceiptType(TimeAnchor:int, TaxCosts:list[dict[str, Any]], *, EnergyCosts:dict[str, Any]|None=None, OccupancyCosts:dict[str, Any]|None=None, AdditionalServicesCosts:dict[str, Any]|None=None, OverstayCosts:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "TaxCosts": {"arrayLen": len(TaxCosts), "array": TaxCosts}
    }
    if EnergyCosts is not None:
        j["EnergyCosts"] = EnergyCosts
    if OccupancyCosts is not None:
        j["OccupancyCosts"] = OccupancyCosts
    if AdditionalServicesCosts is not None:
        j["AdditionalServicesCosts"] = AdditionalServicesCosts
    if OverstayCosts is not None:
        j["OverstayCosts"] = OverstayCosts
    return j

def AbsolutePriceScheduleType(TimeAnchor:int, PriceScheduleID:int, Currency:str, Language:str, PriceAlgorithm:str, PriceRuleStacks:dict[str, Any], *, Id:str|None=None, PriceScheduleDescription:str|None=None, MinimumCost:dict[str, Any]|None=None, MaximumCost:dict[str, Any]|None=None, TaxRules:dict[str, Any]|None=None, OverstayRules:dict[str, Any]|None=None, AdditionalSelectedServices:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "PriceScheduleID": PriceScheduleID,
        "Currency": {"characters": [ord(c) for c in Currency], "charactersLen": len(Currency)},
        "Language": {"characters": [ord(c) for c in Language], "charactersLen": len(Language)},
        "PriceAlgorithm": {"characters": [ord(c) for c in PriceAlgorithm], "charactersLen": len(PriceAlgorithm)},
        "PriceRuleStacks": PriceRuleStacks
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if PriceScheduleDescription is not None:
        j["PriceScheduleDescription"] = {"characters": [ord(c) for c in PriceScheduleDescription], "charactersLen": len(PriceScheduleDescription)}
    if MinimumCost is not None:
        j["MinimumCost"] = MinimumCost
    if MaximumCost is not None:
        j["MaximumCost"] = MaximumCost
    if TaxRules is not None:
        j["TaxRules"] = TaxRules
    if OverstayRules is not None:
        j["OverstayRules"] = OverstayRules
    if AdditionalSelectedServices is not None:
        j["AdditionalSelectedServices"] = AdditionalSelectedServices
    return j

def EVPowerProfileEntryListType(EVPowerProfileEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPowerProfileEntry": {"arrayLen": len(EVPowerProfileEntry), "array": EVPowerProfileEntry}
    }
    return j

def Dynamic_SMDTControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def EVEnergyOfferType(EVPowerSchedule:dict[str, Any], EVAbsolutePriceSchedule:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPowerSchedule": EVPowerSchedule,
        "EVAbsolutePriceSchedule": EVAbsolutePriceSchedule
    }
    return j

def PriceLevelScheduleType(TimeAnchor:int, PriceScheduleID:int, NumberOfPriceLevels:int, PriceLevelScheduleEntries:dict[str, Any], *, Id:str|None=None, PriceScheduleDescription:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "PriceScheduleID": PriceScheduleID,
        "NumberOfPriceLevels": NumberOfPriceLevels,
        "PriceLevelScheduleEntries": PriceLevelScheduleEntries
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if PriceScheduleDescription is not None:
        j["PriceScheduleDescription"] = {"characters": [ord(c) for c in PriceScheduleDescription], "charactersLen": len(PriceScheduleDescription)}
    return j

def ChargingScheduleType(PowerSchedule:dict[str, Any], *, AbsolutePriceSchedule:dict[str, Any]|None=None, PriceLevelSchedule:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "PowerSchedule": PowerSchedule
    }
    if AbsolutePriceSchedule is not None:
        j["AbsolutePriceSchedule"] = AbsolutePriceSchedule
    if PriceLevelSchedule is not None:
        j["PriceLevelSchedule"] = PriceLevelSchedule
    return j

def ScheduleTupleType(ScheduleTupleID:int, ChargingSchedule:dict[str, Any], *, DischargingSchedule:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ScheduleTupleID": ScheduleTupleID,
        "ChargingSchedule": ChargingSchedule
    }
    if DischargingSchedule is not None:
        j["DischargingSchedule"] = DischargingSchedule
    return j

def Scheduled_SMDTControlModeType(SelectedScheduleTupleID:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedScheduleTupleID": SelectedScheduleTupleID
    }
    return j

def MessageHeaderType(SessionID:bytearray, TimeStamp:int, *, Signature:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "TimeStamp": TimeStamp
    }
    if Signature is not None:
        j["Signature"] = Signature
    return j

def SignaturePropertyType(Target:str, *, Id:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Target": {"characters": [ord(c) for c in Target], "charactersLen": len(Target)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ServiceIDListType(ServiceID:list[int])->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": {"arrayLen": len(ServiceID), "array": list(ServiceID)}
    }
    return j

def SelectedServiceType(ServiceID:int, ParameterSetID:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID,
        "ParameterSetID": ParameterSetID
    }
    return j

def SignedMeteringDataType(Id:str, SessionID:bytearray, MeterInfo:dict[str, Any], *, Receipt:dict[str, Any]|None=None, Dynamic_SMDTControlMode:dict[str, Any]|None=None, Scheduled_SMDTControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "MeterInfo": MeterInfo
    }
    if Receipt is not None:
        j["Receipt"] = Receipt
    if Dynamic_SMDTControlMode is not None:
        j["Dynamic_SMDTControlMode"] = Dynamic_SMDTControlMode
    if Scheduled_SMDTControlMode is not None:
        j["Scheduled_SMDTControlMode"] = Scheduled_SMDTControlMode
    return j

def SignedCertificateChainType(Id:str, Certificate:bytearray, *, SubCertificates:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)}
    }
    if SubCertificates is not None:
        j["SubCertificates"] = SubCertificates
    return j

def EIM_AReqAuthorizationModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def SelectedServiceListType(SelectedService:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedService": {"arrayLen": len(SelectedService), "array": SelectedService}
    }
    return j

def Dynamic_SEReqControlModeType(DepartureTime:int, EVTargetEnergyRequest:dict[str, Any], EVMaximumEnergyRequest:dict[str, Any], EVMinimumEnergyRequest:dict[str, Any], *, MinimumSOC:int|None=None, TargetSOC:int|None=None, EVMaximumV2XEnergyRequest:dict[str, Any]|None=None, EVMinimumV2XEnergyRequest:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DepartureTime": DepartureTime,
        "EVTargetEnergyRequest": EVTargetEnergyRequest,
        "EVMaximumEnergyRequest": EVMaximumEnergyRequest,
        "EVMinimumEnergyRequest": EVMinimumEnergyRequest
    }
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if EVMaximumV2XEnergyRequest is not None:
        j["EVMaximumV2XEnergyRequest"] = EVMaximumV2XEnergyRequest
    if EVMinimumV2XEnergyRequest is not None:
        j["EVMinimumV2XEnergyRequest"] = EVMinimumV2XEnergyRequest
    return j

def EVSEStatusType(NotificationMaxDelay:int, EVSENotification:evseNotificationType)->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value
    }
    return j

def ListOfRootCertificateIDsType(RootCertificateID:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "RootCertificateID": {"arrayLen": len(RootCertificateID), "array": RootCertificateID}
    }
    return j

def PnC_AReqAuthorizationModeType(Id:str, GenChallenge:bytearray, ContractCertificateChain:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "GenChallenge": {"bytes": list(GenChallenge), "bytesLen": len(GenChallenge)},
        "ContractCertificateChain": ContractCertificateChain
    }
    return j

def ServiceListType(Service:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "Service": {"arrayLen": len(Service), "array": Service}
    }
    return j

def ServiceParameterListType(ParameterSet:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSet": {"arrayLen": len(ParameterSet), "array": ParameterSet}
    }
    return j

def Scheduled_SEReqControlModeType(*, DepartureTime:int|None=None, EVTargetEnergyRequest:dict[str, Any]|None=None, EVMaximumEnergyRequest:dict[str, Any]|None=None, EVMinimumEnergyRequest:dict[str, Any]|None=None, EVEnergyOffer:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if EVTargetEnergyRequest is not None:
        j["EVTargetEnergyRequest"] = EVTargetEnergyRequest
    if EVMaximumEnergyRequest is not None:
        j["EVMaximumEnergyRequest"] = EVMaximumEnergyRequest
    if EVMinimumEnergyRequest is not None:
        j["EVMinimumEnergyRequest"] = EVMinimumEnergyRequest
    if EVEnergyOffer is not None:
        j["EVEnergyOffer"] = EVEnergyOffer
    return j

def EVPowerProfileType(TimeAnchor:int, EVPowerProfileEntries:dict[str, Any], *, Dynamic_EVPPTControlMode:dict[str, Any]|None=None, Scheduled_EVPPTControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "EVPowerProfileEntries": EVPowerProfileEntries
    }
    if Dynamic_EVPPTControlMode is not None:
        j["Dynamic_EVPPTControlMode"] = Dynamic_EVPPTControlMode
    if Scheduled_EVPPTControlMode is not None:
        j["Scheduled_EVPPTControlMode"] = Scheduled_EVPPTControlMode
    return j

def CertificateChainType(Certificate:bytearray, *, SubCertificates:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)}
    }
    if SubCertificates is not None:
        j["SubCertificates"] = SubCertificates
    return j

def EIM_ASResAuthorizationModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def Dynamic_SEResControlModeType(*, DepartureTime:int|None=None, MinimumSOC:int|None=None, TargetSOC:int|None=None, AbsolutePriceSchedule:dict[str, Any]|None=None, PriceLevelSchedule:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if AbsolutePriceSchedule is not None:
        j["AbsolutePriceSchedule"] = AbsolutePriceSchedule
    if PriceLevelSchedule is not None:
        j["PriceLevelSchedule"] = PriceLevelSchedule
    return j

def EMAIDListType(EMAID:list[str])->dict[str, Any]:
    j:dict[str, Any] = {
        "EMAID": {"arrayLen": len(EMAID), "array": [{"characters": [ord(_c) for _c in _s], "charactersLen": len(_s)} for _s in EMAID]}
    }
    return j

def SignedInstallationDataType(Id:str, ContractCertificateChain:dict[str, Any], ECDHCurve:ecdhCurveType, DHPublicKey:bytearray, *, SECP521_EncryptedPrivateKey:bytearray|None=None, X448_EncryptedPrivateKey:bytearray|None=None, TPM_EncryptedPrivateKey:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "ContractCertificateChain": ContractCertificateChain,
        "ECDHCurve": ECDHCurve.value,
        "DHPublicKey": {"bytes": list(DHPublicKey), "bytesLen": len(DHPublicKey)}
    }
    if SECP521_EncryptedPrivateKey is not None:
        j["SECP521_EncryptedPrivateKey"] = {"bytes": list(SECP521_EncryptedPrivateKey), "bytesLen": len(SECP521_EncryptedPrivateKey)}
    if X448_EncryptedPrivateKey is not None:
        j["X448_EncryptedPrivateKey"] = {"bytes": list(X448_EncryptedPrivateKey), "bytesLen": len(X448_EncryptedPrivateKey)}
    if TPM_EncryptedPrivateKey is not None:
        j["TPM_EncryptedPrivateKey"] = {"bytes": list(TPM_EncryptedPrivateKey), "bytesLen": len(TPM_EncryptedPrivateKey)}
    return j

def PnC_ASResAuthorizationModeType(GenChallenge:bytearray, *, SupportedProviders:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "GenChallenge": {"bytes": list(GenChallenge), "bytesLen": len(GenChallenge)}
    }
    if SupportedProviders is not None:
        j["SupportedProviders"] = SupportedProviders
    return j

def Scheduled_SEResControlModeType(ScheduleTuple:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ScheduleTuple": {"arrayLen": len(ScheduleTuple), "array": ScheduleTuple}
    }
    return j

def SessionSetupReqType(Header:dict[str, Any], EVCCID:str)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVCCID": {"characters": [ord(c) for c in EVCCID], "charactersLen": len(EVCCID)}
    }
    return j

def SessionSetupResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEID:str)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEID": {"characters": [ord(c) for c in EVSEID], "charactersLen": len(EVSEID)}
    }
    return j

def AuthorizationSetupReqType(Header:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header
    }
    return j

def AuthorizationSetupResType(Header:dict[str, Any], ResponseCode:responseCodeType, AuthorizationServices:list[authorizationType], CertificateInstallationService:int, *, EIM_ASResAuthorizationMode:dict[str, Any]|None=None, PnC_ASResAuthorizationMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "AuthorizationServices": {"arrayLen": len(AuthorizationServices), "array": [_v.value for _v in AuthorizationServices]},
        "CertificateInstallationService": CertificateInstallationService
    }
    if EIM_ASResAuthorizationMode is not None:
        j["EIM_ASResAuthorizationMode"] = EIM_ASResAuthorizationMode
    if PnC_ASResAuthorizationMode is not None:
        j["PnC_ASResAuthorizationMode"] = PnC_ASResAuthorizationMode
    return j

def AuthorizationReqType(Header:dict[str, Any], SelectedAuthorizationService:authorizationType, *, EIM_AReqAuthorizationMode:dict[str, Any]|None=None, PnC_AReqAuthorizationMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "SelectedAuthorizationService": SelectedAuthorizationService.value
    }
    if EIM_AReqAuthorizationMode is not None:
        j["EIM_AReqAuthorizationMode"] = EIM_AReqAuthorizationMode
    if PnC_AReqAuthorizationMode is not None:
        j["PnC_AReqAuthorizationMode"] = PnC_AReqAuthorizationMode
    return j

def AuthorizationResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    return j

def ServiceDiscoveryReqType(Header:dict[str, Any], *, SupportedServiceIDs:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header
    }
    if SupportedServiceIDs is not None:
        j["SupportedServiceIDs"] = SupportedServiceIDs
    return j

def ServiceDiscoveryResType(Header:dict[str, Any], ResponseCode:responseCodeType, ServiceRenegotiationSupported:int, EnergyTransferServiceList:dict[str, Any], *, VASList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "ServiceRenegotiationSupported": ServiceRenegotiationSupported,
        "EnergyTransferServiceList": EnergyTransferServiceList
    }
    if VASList is not None:
        j["VASList"] = VASList
    return j

def ServiceDetailReqType(Header:dict[str, Any], ServiceID:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ServiceID": ServiceID
    }
    return j

def ServiceDetailResType(Header:dict[str, Any], ResponseCode:responseCodeType, ServiceID:int, ServiceParameterList:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "ServiceID": ServiceID,
        "ServiceParameterList": ServiceParameterList
    }
    return j

def ServiceSelectionReqType(Header:dict[str, Any], SelectedEnergyTransferService:dict[str, Any], *, SelectedVASList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "SelectedEnergyTransferService": SelectedEnergyTransferService
    }
    if SelectedVASList is not None:
        j["SelectedVASList"] = SelectedVASList
    return j

def ServiceSelectionResType(Header:dict[str, Any], ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    return j

def ScheduleExchangeReqType(Header:dict[str, Any], MaximumSupportingPoints:int, *, Dynamic_SEReqControlMode:dict[str, Any]|None=None, Scheduled_SEReqControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "MaximumSupportingPoints": MaximumSupportingPoints
    }
    if Dynamic_SEReqControlMode is not None:
        j["Dynamic_SEReqControlMode"] = Dynamic_SEReqControlMode
    if Scheduled_SEReqControlMode is not None:
        j["Scheduled_SEReqControlMode"] = Scheduled_SEReqControlMode
    return j

def ScheduleExchangeResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType, *, GoToPause:int|None=None, Dynamic_SEResControlMode:dict[str, Any]|None=None, Scheduled_SEResControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if GoToPause is not None:
        j["GoToPause"] = GoToPause
    if Dynamic_SEResControlMode is not None:
        j["Dynamic_SEResControlMode"] = Dynamic_SEResControlMode
    if Scheduled_SEResControlMode is not None:
        j["Scheduled_SEResControlMode"] = Scheduled_SEResControlMode
    return j

def PowerDeliveryReqType(Header:dict[str, Any], EVProcessing:processingType, ChargeProgress:chargeProgressType, *, EVPowerProfile:dict[str, Any]|None=None, BPT_ChannelSelection:channelSelectionType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVProcessing": EVProcessing.value,
        "ChargeProgress": ChargeProgress.value
    }
    if EVPowerProfile is not None:
        j["EVPowerProfile"] = EVPowerProfile
    if BPT_ChannelSelection is not None:
        j["BPT_ChannelSelection"] = BPT_ChannelSelection.value
    return j

def PowerDeliveryResType(Header:dict[str, Any], ResponseCode:responseCodeType, *, EVSEStatus:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    return j

def MeteringConfirmationReqType(Header:dict[str, Any], SignedMeteringData:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "SignedMeteringData": SignedMeteringData
    }
    return j

def MeteringConfirmationResType(Header:dict[str, Any], ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    return j

def SessionStopReqType(Header:dict[str, Any], ChargingSession:chargingSessionType, *, EVTerminationCode:str|None=None, EVTerminationExplanation:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ChargingSession": ChargingSession.value
    }
    if EVTerminationCode is not None:
        j["EVTerminationCode"] = {"characters": [ord(c) for c in EVTerminationCode], "charactersLen": len(EVTerminationCode)}
    if EVTerminationExplanation is not None:
        j["EVTerminationExplanation"] = {"characters": [ord(c) for c in EVTerminationExplanation], "charactersLen": len(EVTerminationExplanation)}
    return j

def SessionStopResType(Header:dict[str, Any], ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    return j

def CertificateInstallationReqType(Header:dict[str, Any], OEMProvisioningCertificateChain:dict[str, Any], ListOfRootCertificateIDs:dict[str, Any], MaximumContractCertificateChains:int, *, PrioritizedEMAIDs:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "OEMProvisioningCertificateChain": OEMProvisioningCertificateChain,
        "ListOfRootCertificateIDs": ListOfRootCertificateIDs,
        "MaximumContractCertificateChains": MaximumContractCertificateChains
    }
    if PrioritizedEMAIDs is not None:
        j["PrioritizedEMAIDs"] = PrioritizedEMAIDs
    return j

def CertificateInstallationResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType, CPSCertificateChain:dict[str, Any], SignedInstallationData:dict[str, Any], RemainingContractCertificateChains:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value,
        "CPSCertificateChain": CPSCertificateChain,
        "SignedInstallationData": SignedInstallationData,
        "RemainingContractCertificateChains": RemainingContractCertificateChains
    }
    return j

def VehicleCheckInReqType(Header:dict[str, Any], EVCheckInStatus:evCheckInStatusType, ParkingMethod:parkingMethodType, *, VehicleFrame:int|None=None, DeviceOffset:int|None=None, VehicleTravel:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVCheckInStatus": EVCheckInStatus.value,
        "ParkingMethod": ParkingMethod.value
    }
    if VehicleFrame is not None:
        j["VehicleFrame"] = VehicleFrame
    if DeviceOffset is not None:
        j["DeviceOffset"] = DeviceOffset
    if VehicleTravel is not None:
        j["VehicleTravel"] = VehicleTravel
    return j

def VehicleCheckInResType(Header:dict[str, Any], ResponseCode:responseCodeType, *, ParkingSpace:int|None=None, DeviceLocation:int|None=None, TargetDistance:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    if ParkingSpace is not None:
        j["ParkingSpace"] = ParkingSpace
    if DeviceLocation is not None:
        j["DeviceLocation"] = DeviceLocation
    if TargetDistance is not None:
        j["TargetDistance"] = TargetDistance
    return j

def VehicleCheckOutReqType(Header:dict[str, Any], EVCheckOutStatus:evCheckOutStatusType, CheckOutTime:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVCheckOutStatus": EVCheckOutStatus.value,
        "CheckOutTime": CheckOutTime
    }
    return j

def VehicleCheckOutResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSECheckOutStatus:evseCheckOutStatusType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSECheckOutStatus": EVSECheckOutStatus.value
    }
    return j

def CLReqControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def CLResControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ManifestType(Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignaturePropertiesType(SignatureProperty:dict[str, Any], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignatureProperty": SignatureProperty
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def exiFragment(*, AbsolutePriceSchedule:dict[str, Any]|None=None, OEMProvisioningCertificateChain:dict[str, Any]|None=None, PnC_AReqAuthorizationMode:dict[str, Any]|None=None, PriceLevelSchedule:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None, SignedInstallationData:dict[str, Any]|None=None, SignedMeteringData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if AbsolutePriceSchedule is not None:
        j["AbsolutePriceSchedule"] = AbsolutePriceSchedule
    if OEMProvisioningCertificateChain is not None:
        j["OEMProvisioningCertificateChain"] = OEMProvisioningCertificateChain
    if PnC_AReqAuthorizationMode is not None:
        j["PnC_AReqAuthorizationMode"] = PnC_AReqAuthorizationMode
    if PriceLevelSchedule is not None:
        j["PriceLevelSchedule"] = PriceLevelSchedule
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    if SignedInstallationData is not None:
        j["SignedInstallationData"] = SignedInstallationData
    if SignedMeteringData is not None:
        j["SignedMeteringData"] = SignedMeteringData
    return j

def xmldsigFragment(*, CanonicalizationMethod:dict[str, Any]|None=None, DSAKeyValue:dict[str, Any]|None=None, DigestMethod:dict[str, Any]|None=None, KeyInfo:dict[str, Any]|None=None, KeyValue:dict[str, Any]|None=None, Manifest:dict[str, Any]|None=None, Object:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, Reference:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, Signature:dict[str, Any]|None=None, SignatureMethod:dict[str, Any]|None=None, SignatureProperties:dict[str, Any]|None=None, SignatureProperty:dict[str, Any]|None=None, SignatureValue:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None, Transform:dict[str, Any]|None=None, Transforms:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, X509IssuerSerial:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if CanonicalizationMethod is not None:
        j["CanonicalizationMethod"] = CanonicalizationMethod
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if DigestMethod is not None:
        j["DigestMethod"] = DigestMethod
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if Manifest is not None:
        j["Manifest"] = Manifest
    if Object is not None:
        j["Object"] = Object
    if PGPData is not None:
        j["PGPData"] = PGPData
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if Reference is not None:
        j["Reference"] = Reference
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if Signature is not None:
        j["Signature"] = Signature
    if SignatureMethod is not None:
        j["SignatureMethod"] = SignatureMethod
    if SignatureProperties is not None:
        j["SignatureProperties"] = SignatureProperties
    if SignatureProperty is not None:
        j["SignatureProperty"] = SignatureProperty
    if SignatureValue is not None:
        j["SignatureValue"] = SignatureValue
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    if Transform is not None:
        j["Transform"] = Transform
    if Transforms is not None:
        j["Transforms"] = Transforms
    if X509Data is not None:
        j["X509Data"] = X509Data
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    return j
